language: node_js
node_js:
- lts/erbium
cache:
  directories:
  - node_modules
after_success:
- npm run build
deploy:
- provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "dmP+achpzvH4joD3OBDMuFtLLTWjZqPiYfbuUdoj+T7j4B5l1IpvIYGVDA9hqMyvfDhLekDdYHu3SI1mv3A9QG8HLVtclOhj7oJjoty8eoU+gjRwh5phnuENgvo7mS4NnWvzZUZSMEKYrKQUjSqMmBtu3J+ZPpt9clJLXgWOV96QpnqO1xpX+HaUPokxNTsB5TznwmWGKjZMQkT02hNn9TV5+A8REo4VWI5/J0atwsM58iMYcuqaZeqKvAeqcesQXtjZAVUX1flr/SbVVzx0Okkg/7QP1a4NvZR/PND27WIF92Rdu6R1aj7zsNdjEuGQ/lcCu7hDA/hUqzD6CcLsvIYrBvC9tTsuWk9G7yUFKyZlLIHlZ4LIQjAJYA5Vob5gGbXzmg2xboBbBpTI6xJp4Sq0qrbaZ2zI/VkBthyBTmnO7e2QXs20rOHcOmWvqyvppZoWqSrcIVRhjgQ02lBqOGKc6rO72UPbsqOJjyTybLnPNAvuleRAwHqmkh+SvR/Xk/nidBW46bdHm+kZgPFBrjSc+W+Uwso9mBhgazcthhk8ZxYORkOgBiYCy7TCfUNf8cX/+tYY0qLYO1RY8Mnv2q3m/E/hoM29Psk7LyrZWDX3jWJedLkeyE2UBql9pgIJiLCRORfHy5tJc8n2zwDAkwbZ1TQl1ZBLYhhKqTa82p4="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
